version: "3"
services:
  server:
    image: gitgiter/baobaozhuan_server:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8080:8080"
    networks:
      - webnet
  db:
    image: mysql:5.7.25
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SYSU_baobaozhuan2019
      PMA_HOST: mysql
    networks:
      - webnet
  nginx:
    image: nginx:1.12.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    volumes:
      - /etc/nginx:/etc/nginx
    ports:
      - "443:443"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9999:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis:5.0.2
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet: